export const SECRETARIATS = [
  'Controladoria Geral do Município - CGM',
  'Secretaria Municipal da Fazenda - SEFAZ',
  'Secretaria Municipal do Meio Ambiente, Gestão Urbana e Desenvolvimento Econômico, Turístico e Sustentável - SEMADES',
  'Secretaria Municipal de Saúde - SESAU',
  'Secretaria de Assistência Social e Cidadania - SAS',
  'Secretaria Executiva da Cultura - SECULT',
  'Secretaria Municipal de Administração e Inovação - SEMADI',
  'Secretaria Executiva da Juventude - SEJUV',
  'Secretaria Municipal de Educação - SEMED',
  'Secretaria Especial de Segurança e Defesa Social - SESDES',
  'Secretaria Municipal de Infraestrutura e Serviços Públicos - SISEP',
  'Instituto Municipal de Previdência de Campo Grande - IMPCG',
  'Agência Municipal de Meio Ambiente e Planejamento Urbano - PLANURB',
  'Agência Municipal de Tecnologia da Informação e Inovação - AGETEC',
  'Agência Municipal de Transporte e Trânsito - AGETRAN',
  'Agência Municipal de Habitação e Assuntos Fundiários - EMHA',
  'Fundação Municipal de Esportes - FUNESP',
  'Fundação Social do Trabalho de Campo Grande - FUNSAT',
  'Fundo de Apoio à Comunidade - FAC',
  'Secretaria Executiva da Mulher - SEMU',
  'Secretaria Especial de Articulação Regional - SEAR',
];
